import { useMediaQuery } from "react-responsive";

import CountrySelectionManager from "../components/CountrySelectionManager";
import HeaderNavMobile from "../components/HeaderNavMobile";
import HeaderNavDesktop from "../components/HeaderNavDesktop";
import RecommandedList from "../components/RecommandedList";
import PopularList from "../components/PopularList";
import ModalManager from "../components/ModalManager";
import LikeSection from "../components/LikeSection";
import ManageLikes from "../components/LikeDestinationsManagers";

const destinations = [
  {
    ID: 1,
    Name: "Mexico",
    Src: "https://www.acs-ami.com/fr/blog/wp-content/uploads/2021/10/visiter-le-mexique-1.jpg",
    Label: "Latin America",
    Text: "Discover Mexico, a country rich in history, culture, and diverse landscapes.",
    TextDesktop:
      "From its tropical beaches to archaeological sites, every corner of Mexico offers a unique experience. Enjoy delicious cuisine, picturesque colonial towns, and colorful festivities.",
    isFavorite: true,
    Capital: "Mexico City",
    CountryCode: "mx",
    Currency: "MXN",
    TimeZone: "America/Mexico_City",
  },
  {
    ID: 2,
    Name: "Vietnam",
    Src: "https://media.istockphoto.com/id/186977241/fr/photo/%C3%AEles-pr%C3%A8s-de-rock-village-flottant-dans-la-baie-dhalong.jpg?s=612x612&w=0&k=20&c=1fT_vtJn6Am_m_WQzkuzPi4Nktteb2ihbWcoYxbscF8=",
    Label: "Asia",
    Text: "Discover Vietnam, an enchanting destination in Southeast Asia.",
    TextDesktop:
      "In Vietnam, lush green terraced rice fields and spectacular karstic bays like Ha Long await you. Immerse yourself in Vietnam's captivating history and vibrant culture.",
    isFavorite: false,
    Capital: "Hanoi",
    CountryCode: "vn",
    Currency: "VND",
    TimeZone: "Asia/Ho_Chi_Minh",
  },
  {
    ID: 3,
    Name: "United Kingdom",
    Src: "https://www.shutterstock.com/image-photo/big-ben-bridge-over-thames-600nw-2209687145.jpg",
    Label: "Europe",
    Text: "Explore the United Kingdom, a fascinating and diverse destination in Europe.",
    TextDesktop:
      "England is renowned for its unique blend of tradition and modernity. From majestic medieval castles to bustling cities like London, discover the rich history and dynamic culture of the UK.",
    isFavorite: false,
    Capital: "London",
    CountryCode: "gb",
    Currency: "GBP",
    TimeZone: "Europe/London",
  },
  {
    ID: 4,
    Name: "Argentina",
    Src: "https://photos.tui.fr/vnf/Produits/ARGCT015-circuits-argentine-chili-tui.jpg",
    Label: "Latin America",
    Text: "Immerse yourself in adventure in Argentina, a country offering breathtaking landscapes.",
    TextDesktop:
      "Explore exciting cities like Buenos Aires, feel the rhythm of tango, and discover a culture rich in traditions and passion for football.",
    isFavorite: false,
    Capital: "Buenos Aires",
    CountryCode: "ar",
    Currency: "ARS",
    TimeZone: "America/Argentina/Buenos_Aires",
  },
  {
    ID: 5,
    Name: "Morocco",
    Src: "https://trvlr.fr/wp-content/uploads/2020/10/maroc-trvlr-guide-destination-digital.jpg",
    Label: "Africa",
    Text: "Embark on a journey to Morocco, a magical country in North Africa.",
    TextDesktop:
      "In this country where the desert meets the sea and majestic mountains, immerse yourself in the enchanting atmosphere of lively souks, splendid palaces, and narrow streets of historic medinas.",
    isFavorite: false,
    Capital: "Rabat",
    CountryCode: "ma",
    Currency: "MAD",
    TimeZone: "Africa/Casablanca",
  },
  {
    ID: 6,
    Name: "Andorra",
    Src: "https://media.istockphoto.com/id/1187845438/fr/photo/vue-a%C3%A9rienne-de-la-station-de-ski-de-grandvalira-dans-le-pas-de-la-casa.jpg?s=612x612&w=0&k=20&c=wCTQZfNvNlu4BYDd4CXrLv59Z0dTQX_QUYRbHnwIWcA=",
    Label: "Europe",
    Text: "A small mountainous country known for its ski resorts, picturesque landscapes, and status as a tax haven.",
    TextDesktop:
      "Andorra, nestled in the Pyrenees between France and Spain, offers a unique experience blending nature, culture, and shopping. Famous for its ski resorts, duty-free shopping centers, and spectacular mountain landscapes.",
    isFavorite: false,
    Capital: "Andorra la Vella",
    CountryCode: "ad",
    Currency: "EUR",
    TimeZone: "Europe/Andorra",
  },
  {
    ID: 7,
    Name: "Albania",
    Src: "https://media.istockphoto.com/id/529358575/fr/photo/saranda-le-port-de-la-mer-ionienne-albanie.jpg?s=612x612&w=0&k=20&c=ia5GWBtH529Hu7VbVY8NX2wEPK3Lda-9SUHZzrRmqYA=",
    Label: "Europe",
    Text: "Discover its majestic mountains, picturesque beaches, and rich cultural heritage.",
    TextDesktop:
      "Albania, located in Southeast Europe, is known for its majestic mountains, picturesque beaches, and rich cultural heritage. The country offers a fascinating history, delicious cuisine, and warm hospitality.",
    isFavorite: false,
    Capital: "Tirana",
    CountryCode: "al",
    Currency: "ALL",
    TimeZone: "Europe/Tirane",
  },
  {
    ID: 8,
    Name: "Armenia",
    Src: "https://cdn.pixabay.com/photo/2020/04/09/14/07/armenia-5021630_1280.jpg",
    Label: "Europe",
    Text: "Explore a mountainous country with a rich history and ancient culture.",
    TextDesktop:
      "Armenia is one of the oldest continuously inhabited cities in the world, famous for its pink-hued architecture and numerous historical sites.",
    isFavorite: false,
    Capital: "Yerevan",
    CountryCode: "am",
    Currency: "AMD",
    TimeZone: "Europe/Samara",
  },
  {
    ID: 9,
    Name: "Austria",
    Src: "https://cdn.pixabay.com/photo/2017/11/30/23/28/vienna-2989756_640.jpg",
    Label: "Europe",
    Text: "Discover a country known for its stunning Alpine landscapes, historic cities, and rich culture.",
    TextDesktop:
      "Austria is renowned for its imperial architecture, renowned museums, and vibrant artistic scene. The country is also famous for its classical music.",
    isFavorite: false,
    Capital: "Vienna",
    CountryCode: "at",
    Currency: "EUR",
    TimeZone: "Europe/Vienna",
  },
  {
    ID: 10,
    Name: "Australia",
    Src: "https://cdn.pixabay.com/photo/2014/05/26/09/58/sydney-opera-house-354375_1280.jpg",
    Label: "Oceania",
    Text: "Australia is an island country located in the Southern Hemisphere, famous for its natural diversity, dynamic cities, Aboriginal culture, and unique wildlife.",
    TextDesktop:
      "Australia is renowned for its diverse landscapes, ranging from pristine beaches to arid deserts, and lush tropical forests.",
    isFavorite: false,
    Capital: "Canberra",
    CountryCode: "au",
    Currency: "AUD",
    TimeZone: "Australia/Sydney",
  },

  {
    ID: 11,
    Name: "Åland Islands",
    Src: "https://cdn.pixabay.com/photo/2017/10/02/20/28/mariehamn-2810073_640.jpg",
    Label: "Europe",
    Text: "The Åland Islands are known for their natural beauty, picturesque marine landscapes, and distinctive culture.",
    TextDesktop:
      "An autonomous region of Finland, located in the Baltic Sea between Sweden and Finland. They are mainly inhabited by Swedish speakers and have had autonomous status since 1921.",
    isFavorite: false,
    Capital: "Mariehamn",
    CountryCode: "ax",
    Currency: "EUR",
    TimeZone: "Europe/Athens",
  },
  {
    ID: 12,
    Name: "Bosnia and Herzegovina",
    Src: "https://media.istockphoto.com/id/585067008/photo/mostar-bridge-bosnia-and-herzegovina.jpg?s=612x612&w=0&k=20&c=4_NgcTg6oWiXjpLS4LIObS8qxpFzZ7R-71GOd_QFRcw=",
    Label: "Europe",
    Text: "Bosnia and Herzegovina is a country in the Balkans, marked by its cultural diversity and complex history.",
    TextDesktop:
      "Bosnia and Herzegovina is known for its unique blend of Eastern and Western influences. The country is dotted with magnificent mountain landscapes, crystalline rivers, and historic sites.",
    isFavorite: false,
    Capital: "Sarajevo",
    CountryCode: "ba",
    Currency: "BAM",
    TimeZone: "Europe/Paris",
  },
  {
    ID: 13,
    Name: "Barbados",
    Src: "https://cdn.pixabay.com/photo/2020/06/13/10/43/wallpaper-5293774_1280.jpg",
    Label: "North America",
    Text: "Explore one of the Caribbean islands, renowned for its white sandy beaches, turquoise waters, and coral reefs.",
    TextDesktop:
      "Barbados, a Caribbean island that offers vibrant culture, delicious cuisine, and warm hospitality.",
    isFavorite: false,
    Capital: "Bridgetown",
    CountryCode: "bb",
    Currency: "BBD",
    TimeZone: "America/Barbados",
  },
  {
    ID: 14,
    Name: "Belgium",
    Src: "https://cdn.pixabay.com/photo/2018/08/14/20/36/mini-europe-3606552_1280.jpg",
    Label: "Europe",
    Text: "Discover picturesque cities such as Brussels, Bruges, and Antwerp.",
    TextDesktop:
      "Belgium is a European country known for its rich history, cultural diversity, delicious waffles, and chocolates.",
    isFavorite: false,
    Capital: "Brussels",
    CountryCode: "be",
    Currency: "EUR",
    TimeZone: "Europe/Brussels",
  },
  {
    ID: 15,
    Name: "Bulgaria",
    Src: "https://cdn.pixabay.com/photo/2022/08/10/19/24/landscape-7378004_640.jpg",
    Label: "Europe",
    Text: "Discover its mountains, beaches along the Black Sea, and rich cultural history.",
    TextDesktop:
      "Bulgaria is a country located in southeastern Europe, bordered by the Black Sea to the east. It is known for its mountains, ski resorts, beaches, and rich cultural history.",
    isFavorite: false,
    Capital: "Sofia",
    CountryCode: "bg",
    Currency: "BGN",
    TimeZone: "Europe/Sofia",
  },
  {
    ID: 16,
    Name: "Benin",
    Src: "https://cdn.pixabay.com/photo/2016/01/13/17/48/machupicchu-1138641_960_720.jpg",
    Label: "Africa",
    Text: "Dive into a unique cultural and natural richness in West Africa.",
    TextDesktop:
      "Benin, also known as Dahomey, is a country in West Africa. The country is known for its rich history, vibrant culture, and ethnic diversity.",
    isFavorite: false,
    Capital: "Porto-Novo",
    CountryCode: "bj",
    Currency: "XOF",
    TimeZone: "Africa/Tunis",
  },
  {
    ID: 17,
    Name: "Bolivia",
    Src: "https://cdn.pixabay.com/photo/2020/03/10/13/53/flamingos-4919079_1280.jpg",
    Label: "South America",
    Text: "Dive into a country rich in culture, spectacular landscapes, and fascinating traditions.",
    TextDesktop:
      "Bolivia is known for its diverse landscape, including the high plains of the Andes, the Amazon rainforest, and the famous Lake Titicaca. It also houses the famous Salar de Uyuni, the largest salt flat in the world.",
    isFavorite: false,
    Capital: "La Paz",
    CountryCode: "bo",
    Currency: "BOB",
    TimeZone: "America/La_Paz",
  },
  {
    ID: 18,
    Name: "Brazil",
    Src: "https://cdn.pixabay.com/photo/2020/01/31/21/25/brazil-4809011_640.jpg",
    Label: "South America",
    Text: "Explore its natural diversity, discover its rich history, and appreciate the warmth of its welcoming people.",
    TextDesktop:
      "Brazil is a dynamic and diverse country in South America, famous for its vast tropical forests, beautiful beaches, vibrant culture, and love for football.",
    isFavorite: false,
    Capital: "Brasilia",
    CountryCode: "br",
    Currency: "BRL",
    TimeZone: "America/Bahia",
  },
  {
    ID: 19,
    Name: "Bahamas",
    Src: "https://cdn.pixabay.com/photo/2016/01/05/15/58/starfish-1122849_640.jpg",
    Label: "North America",
    Text: "It is a destination renowned for its white sandy beaches, crystal-clear waters, and water activities.",
    TextDesktop:
      "The Bahamas is an archipelago of more than 700 islands located in the Atlantic Ocean, north of Cuba and the Dominican Republic. The Bahamas also offer an abundance of marine life, including dolphins, sea turtles, and sharks.",
    isFavorite: false,
    Capital: "Nassau",
    CountryCode: "bs",
    Currency: "BSD",
    TimeZone: "America/La_Paz",
  },
  {
    ID: 20,
    Name: "Botswana",
    Src: "https://cdn.pixabay.com/photo/2016/09/08/01/38/botswana-1653100_1280.jpg",
    Label: "Africa",
    Text: "Immerse yourself in diverse wildlife, including the famous Okavango Delta.",
    TextDesktop:
      "Botswana, located in southern Africa, is known for its political stability, growing economy, and national parks.",
    isFavorite: false,
    Capital: "Gaborone",
    CountryCode: "bw",
    Currency: "BWP",
    TimeZone: "Africa/Tripoli",
  },

  {
    ID: 21,
    Name: "Belarus",
    Src: "https://cdn.pixabay.com/photo/2021/11/25/13/38/mir-castle-complex-6823633_640.jpg",
    Label: "Europe",
    Text: "Discover its rich history, vast forests, lakes, and well-preserved medieval castles.",
    TextDesktop:
      "Belarus, also known as Belarus, is a country in Eastern Europe, famous for its vast forests, well-preserved medieval castles, and rich history culture",
    isFavorite: false,
    Capital: "Minsk",
    CountryCode: "by",
    Currency: "RUB",
    TimeZone: "Europe/Minsk",
  },
  {
    ID: 22,
    Name: "Belize",
    Src: "https://cdn.pixabay.com/photo/2017/01/06/15/39/turtle-1958058_640.jpg",
    Label: "North America",
    Text: "Discover its natural beauty and rich cultural diversity. Its tourist attractions include white sandy beaches.",
    TextDesktop:
      "Belize is a small country in Central America bordered by the Caribbean Sea to the east. It is known for its barrier reef, the second largest in the world, offering exceptional diving and snorkeling opportunities",
    isFavorite: false,
    Capital: "Belmopan",
    CountryCode: "bz",
    Currency: "BZD",
    TimeZone: "America/Belize",
  },
  {
    ID: 23,
    Name: "Canada",
    Src: "https://cdn.pixabay.com/photo/2017/10/28/07/47/woman-2896389_640.jpg",
    Label: "North America",
    Text: "Explore incredible natural beauty, with diverse landscapes ranging from the majestic Rocky Mountains to the vastness of the Prairies, to the vast boreal forests and the beautiful Atlantic and Pacific coasts.",
    TextDesktop:
      "Canada is a vast country in North America known for its cultural diversity, stunning landscapes, and high quality of life.",
    isFavorite: false,
    Capital: "Ottawa",
    CountryCode: "ca",
    Currency: "CAD",
    TimeZone: "America/Guyana",
  },
  {
    ID: 24,
    Name: "Switzerland",
    Src: "https://cdn.pixabay.com/photo/2020/01/14/15/51/the-cable-car-4765350_640.jpg",
    Label: "Europe",
    Text: "Switzerland is renowned for its picturesque Alpine landscapes, crystal-clear lakes, cosmopolitan cities, and neutral political system.",
    TextDesktop:
      "Switzerland is also famous for its high-quality watches, exquisite chocolate, and tasty cheeses.",
    isFavorite: false,
    Capital: "Bern",
    CountryCode: "ch",
    Currency: "CHF",
    TimeZone: "Europe/Berlin",
  },
  {
    ID: 25,
    Name: "Chile",
    Src: "https://cdn.pixabay.com/photo/2016/06/17/18/45/nature-1463830_1280.jpg",
    Label: "South America",
    Text: "Explore its rich culture and fascinating history.",
    TextDesktop:
      "Chile is a country with varied geography including mountains, deserts, forests, and picturesque coasts. Chile is famous for its vineyards, majestic volcanoes, and impressive glaciers.",
    isFavorite: false,
    Capital: "Santiago",
    CountryCode: "cl",
    Currency: "CLP",
    TimeZone: "America/Santiago",
  },
  {
    ID: 26,
    Name: "China",
    Src: "https://cdn.pixabay.com/photo/2020/08/12/19/28/great-wall-of-china-5483516_640.jpg",
    Label: "Asia",
    Text: "Discover its long history, rich culture, large population, and booming economy.",
    TextDesktop:
      "China is famous for its historical sites like the Great Wall, ancient temples, and diverse natural landscapes. China is a major player on the global stage, both economically and politically",
    isFavorite: false,
    Capital: "Beijing",
    CountryCode: "cn",
    Currency: "CNY",
    TimeZone: "Asia/Shanghai",
  },
  {
    ID: 27,
    Name: "Colombia",
    Src: "https://cdn.pixabay.com/photo/2024/01/23/21/46/canoes-8528338_1280.jpg",
    Label: "South America",
    Text: "Colombia's cultural richness is reflected in its lively festivals, enchanting music, and delicious cuisine.",
    TextDesktop:
      "Colombia is a multifaceted country. It offers incredible diversity, from the white sandy beaches of the Caribbean Sea to the snowy peaks of the Sierra Nevada",
    isFavorite: false,
    Capital: "Bogota",
    CountryCode: "co",
    Currency: "COP",
    TimeZone: "America/Bogota",
  },
  {
    ID: 28,
    Name: "Costa Rica",
    Src: "https://cdn.pixabay.com/photo/2015/04/11/22/15/volcano-718277_640.jpg",
    Label: "Central America",
    Text: "Discover its fascinating museums, bustling markets, and dynamic artistic scene.",
    TextDesktop:
      "Costa Rica is a small country with incredible natural diversity. It is known for its vast tropical forests, paradise beaches, active volcanoes, and exceptional biodiversity.",
    isFavorite: false,
    Capital: "San Jose",
    CountryCode: "cr",
    Currency: "CRC",
    TimeZone: "America/Phoenix",
  },
  {
    ID: 29,
    Name: "Cuba",
    Src: "https://cdn.pixabay.com/photo/2018/04/20/04/26/architecture-3335045_640.jpg",
    Label: "North America",
    Text: "Explore an enchanting Caribbean island, renowned for its rich history, vibrant culture, white sandy beaches, and picturesque colonial cities.",
    TextDesktop:
      "Experience the enchanting music of salsa and Cuban son, the classic cars from the 1950s cruising the colorful streets of Havana, and the well-preserved Spanish colonial architecture.",
    isFavorite: false,
    Capital: "Havana",
    CountryCode: "cu",
    Currency: "CUP",
    TimeZone: "America/Havana",
  },
  {
    ID: 30,
    Name: "Cyprus",
    Src: "https://cdn.pixabay.com/photo/2019/02/03/12/25/kyrenia-3972470_640.jpg",
    Label: "Europe",
    Text: "Discover a sunny island in the eastern Mediterranean, famous for its rich history, vibrant culture, and picturesque landscapes.",
    TextDesktop:
      "Cyprus, an island located in the eastern part of the Mediterranean Sea, is known for its fascinating blend of cultures, rich history, and picturesque landscapes.",
    isFavorite: false,
    Capital: "Nicosia",
    CountryCode: "cy",
    Currency: "EUR",
    TimeZone: "Europe/Istanbul",
  },
  {
    ID: 31,
    Name: "Czechia",
    Src: "https://cdn.pixabay.com/photo/2018/04/20/21/57/bridges-3337124_640.jpg",
    Label: "Europe",
    Text: "Explore Czech landscapes offering great diversity, from the Sudetes and Giant Mountains to wooded plains and picturesque rivers.",
    TextDesktop:
      "The Czech Republic, also known as Czechia, is a country in Central Europe. It is renowned for its magnificent medieval castles and charming historic towns.",
    isFavorite: false,
    Capital: "Prague",
    CountryCode: "cz",
    Currency: "CZK",
    TimeZone: "Europe/Prague",
  },
  {
    ID: 32,
    Name: "Germany",
    Src: "https://cdn.pixabay.com/photo/2022/05/24/16/11/berlin-7218821_1280.jpg",
    Label: "Europe",
    Text: "Famous for its historic landmarks such as the Brandenburg Gate and the Berlin Wall, as well as its contributions to music, philosophy, literature, and art.",
    TextDesktop:
      "Germany is a country in Central Europe known for its rich history, vibrant culture, and cutting-edge technology. Berlin is its capital and one of the most dynamic cities culturally.",
    isFavorite: false,
    Capital: "Berlin",
    CountryCode: "de",
    Currency: "EUR",
    TimeZone: "Europe/Prague",
  },
  {
    ID: 33,
    Name: "Denmark",
    Src: "https://cdn.pixabay.com/photo/2019/03/13/11/04/copenhagen-4052654_640.jpg",
    Label: "Europe",
    Text: "Discover its picturesque landscapes, beautiful islands, and coasts lined with sandy beaches.",
    TextDesktop:
      "The country is also known for its innovative design, modern architecture, and progressive environmental initiatives. Danish culture emphasizes well-being, social equality, and sustainability.",
    isFavorite: false,
    Capital: "Copenhagen",
    CountryCode: "dk",
    Currency: "DKK",
    TimeZone: "Europe/Andorra",
  },
  {
    ID: 34,
    Name: "Dominican Republic",
    Src: "https://cdn.pixabay.com/photo/2017/02/26/12/45/las-galeras-2100152_640.jpg",
    Label: "North America",
    Text: "Explore its culture infused with music and dance, with merengue as the national dance.",
    TextDesktop:
      "The Dominican Republic, located in the Caribbean, is famous for its white sandy beaches, luxurious resorts, and golf courses.",
    isFavorite: false,
    Capital: "Santo Domingo",
    CountryCode: "do",
    Currency: "DOP",
    TimeZone: "America/Santo_Domingo",
  },
  {
    ID: 35,
    Name: "Ecuador",
    Src: "https://cdn.pixabay.com/photo/2019/12/11/13/50/volcano-4688409_640.jpg",
    Label: "South America",
    Text: "Ecuador has a rich indigenous culture and history, with strong Spanish influence after colonization.",
    TextDesktop:
      "Ecuador is a country crossed by the equator line hence its name. It is also known for its volcanoes, spectacular landscapes, and ethnic diversity.",
    isFavorite: false,
    Capital: "Quito",
    CountryCode: "ec",
    Currency: "USD",
    TimeZone: "America/Jamaica",
  },
  {
    ID: 36,
    Name: "Estonia",
    Src: "https://cdn.pixabay.com/photo/2014/12/30/17/14/tallinn-584127_640.jpg",
    Label: "Europe",
    Text: "Discover a country known for its pristine nature, dense forests, lakes, and picturesque coasts.",
    TextDesktop:
      "Estonia is known to be one of the most digitally advanced nations in the world, with a strong online presence in many aspects of daily life including public administration, banking services, and online voting.",
    isFavorite: false,
    Capital: "Tallinn",
    CountryCode: "ee",
    Currency: "EUR",
    TimeZone: "Europe/Tallinn",
  },
  {
    ID: 37,
    Name: "Egypt",
    Src: "https://cdn.pixabay.com/photo/2017/03/20/14/33/pyramids-2159286_640.jpg",
    Label: "Africa",
    Text: "Egypt is known for its rich historical heritage, particularly the pyramids of Giza, the Sphinx, and ancient temples along the Nile.",
    TextDesktop:
      "The country has a fascinating ancient history, with a civilization dating back over 5,000 years.",
    isFavorite: false,
    Capital: "Cairo",
    CountryCode: "eg",
    Currency: "EGP",
    TimeZone: "Africa/Cairo",
  },
  {
    ID: 38,
    Name: "Spain",
    Src: "https://cdn.pixabay.com/photo/2018/06/08/12/58/royal-3462249_640.jpg",
    Label: "Europe",
    Text: "Explore its rich history, vibrant culture, delicious cuisine, beautiful beaches, and lively festivals.",
    TextDesktop:
      "The country is also home to iconic sites such as the Sagrada Familia in Barcelona, the Alhambra in Granada, and the Royal Palace in Madrid.",
    isFavorite: false,
    Capital: "Madrid",
    CountryCode: "es",
    Currency: "EUR",
    TimeZone: "Europe/Madrid",
  },
  {
    ID: 39,
    Name: "Finland",
    Src: "https://cdn.pixabay.com/photo/2019/05/08/22/01/helsinki-cathedral-4189825_640.jpg",
    Label: "Europe",
    Text: "Discover its vast expanses of pristine nature, sparkling lakes, enchanting Northern Lights, and traditional saunas.",
    TextDesktop:
      "Finland is renowned for its high-quality education system, culture of design and innovation, as well as its balanced and wellness-oriented way of life.",
    isFavorite: false,
    Capital: "Helsinki",
    CountryCode: "fi",
    Currency: "EUR",
    TimeZone: "Europe/Helsinki",
  },
  {
    ID: 40,
    Name: "Faroe Islands",
    Src: "https://cdn.pixabay.com/photo/2018/08/30/12/31/klaksvik-harbour-3642055_640.jpg",
    Label: "Europe",
    Text: "The Faroe Islands offer a unique experience for travelers seeking pristine nature, spectacular landscapes, and authentic Nordic culture.",
    TextDesktop:
      "The Faroe Islands are an autonomous Nordic archipelago within the Kingdom of Denmark, offering breathtaking landscapes, rich culture, and preserved nature.",
    isFavorite: false,
    Capital: "Tórshavn",
    CountryCode: "fo",
    Currency: "DKK",
    TimeZone: "Europe/Lisbon",
  },
  {
    ID: 41,
    Name: "France",
    Src: "https://cdn.pixabay.com/photo/2018/04/25/09/26/eiffel-tower-3349075_1280.jpg",
    Label: "Europe",
    Text: "France, the land of elegance, gastronomy, art, and culture, is renowned for its iconic landmarks and varied landscapes.",
    TextDesktop:
      "Discover its refined cuisine, stroll through its charming cobblestone streets, explore its renowned museums, and immerse yourself in its unique way of life.",
    isFavorite: false,
    Capital: "Paris",
    CountryCode: "fr",
    Currency: "EUR",
    TimeZone: "Europe/Paris",
  },
  {
    ID: 42,
    Name: "Gabon",
    Src: "https://cdn.pixabay.com/photo/2021/11/29/16/47/parrot-6833007_640.jpg",
    Label: "Africa",
    Text: "Explore its exceptional biodiversity, vast tropical forests, preserved national parks, and sandy beaches.",
    TextDesktop:
      "Gabon offers a cosmopolitan ambiance with its lively markets, fresh seafood restaurants, and palm-lined avenues.",
    isFavorite: false,
    Capital: "Libreville",
    CountryCode: "ga",
    Currency: "XAF",
    TimeZone: "",
  },
  {
    ID: 43,
    Name: "Grenada",
    Src: "https://media.istockphoto.com/id/484292268/fr/photo/%C3%AEle-st-barth.jpg?s=612x612&w=0&k=20&c=7iSGIW2m18HqTUoDvuR9tcjnzNuEUQv7wl2_OpberyE=",
    Label: "America",
    Text: "Discover a destination offering an idyllic tropical atmosphere, jungle hikes, and relaxation on secluded beaches.",
    TextDesktop:
      "Grenada is a Caribbean island known for its white sandy beaches, crystal-clear waters, lush vegetation, and picturesque mountains.",
    isFavorite: false,
    Capital: "Saint-George's",
    CountryCode: "gd",
    Currency: "XCD",
    TimeZone: "",
  },
  {
    ID: 44,
    Name: "Georgia",
    Src: "https://cdn.pixabay.com/photo/2012/12/19/04/02/atlanta-70847_640.jpg",
    Label: "Europe",
    Text: "Georgia enchants you with its majestic mountains, picturesque vineyards, rich cultural heritage, and ancient traditions.",
    TextDesktop:
      "Georgia is known for its rich history, ancient culture, spectacular mountainous landscapes, as well as its unique cuisine and wines.",
    isFavorite: false,
    Capital: "Tbilisi",
    CountryCode: "ge",
    Currency: "GEL",
    TimeZone: "",
  },
  {
    ID: 45,
    Name: "Guernsey",
    Src: "https://cdn.pixabay.com/photo/2014/10/24/21/44/guernsey-501805_640.jpg",
    Label: "Europe",
    Text: "Explore its golden sandy beaches, discover its rugged cliffs and picturesque hiking trails.",
    TextDesktop:
      "Dive into the island's fascinating history by visiting its medieval castles, museums, and archaeological sites. Also, enjoy its local cuisine.",
    isFavorite: false,
    Capital: "Saint Peter Port",
    CountryCode: "gg",
    Currency: "GBP",
    TimeZone: "",
  },
  {
    ID: 46,
    Name: "Gibraltar",
    Src: "https://cdn.pixabay.com/photo/2018/07/01/12/44/gibraltar-3509369_640.jpg",
    Label: "Europe",
    Text: "Gibraltar is renowned for its iconic rock, spectacular panoramic views of the Mediterranean, and rich and diverse history.",
    TextDesktop:
      "Explore its narrow streets with British and Mediterranean influences, discover its historic sites, and enjoy its sunny beaches and water activities.",
    isFavorite: false,
    Capital: "Gibraltar",
    CountryCode: "gi",
    Currency: "GBP",
    TimeZone: "",
  },
  {
    ID: 47,
    Name: "Greenland",
    Src: "https://cdn.pixabay.com/photo/2015/08/17/13/46/tasiilaq-892503_640.jpg",
    Label: "North America",
    Text: "Discover its impressive landscape dotted with majestic glaciers, deep fjords, and rugged mountains.",
    TextDesktop:
      "Despite its isolation and extreme climate, Greenland offers unique natural beauty and an unforgettable adventure for intrepid travelers.",
    isFavorite: false,
    Capital: "Nuuk",
    CountryCode: "gl",
    Currency: "DKK",
    TimeZone: "",
  },
  {
    ID: 48,
    Name: "Gambia",
    Src: "https://cdn.pixabay.com/photo/2017/08/20/03/31/island-2660539_640.jpg",
    Label: "Africa",
    Text: "Discover its beautiful sandy beaches, picturesque rivers, and lush nature.",
    TextDesktop:
      "Gambian culture is rich in traditions, music, and dance, offering an authentic experience to visitors.",
    isFavorite: false,
    Capital: "Banjul",
    CountryCode: "gm",
    Currency: "GMD",
    TimeZone: "",
  },
  {
    ID: 49,
    Name: "Greece",
    Src: "https://cdn.pixabay.com/photo/2012/02/07/17/12/acropolis-12044_640.jpg",
    Label: "Europe",
    Text: "Greece, the cradle of Western civilization, is a fascinating country where history, mythology, and culture harmoniously blend.",
    TextDesktop:
      "The Greek islands, with their picturesque villages with whitewashed houses and crystal-clear waters, attract visitors from around the world.",
    isFavorite: false,
    Capital: "Athens",
    CountryCode: "gr",
    Currency: "EUR",
    TimeZone: "",
  },
  {
    ID: 50,
    Name: "Guatemala",
    Src: "https://cdn.pixabay.com/photo/2020/07/15/17/44/pyramid-5408477_640.jpg",
    Label: "America",
    Text: "Discover a beautiful country with a rich history, vibrant culture, and diverse landscapes.",
    TextDesktop:
      "Guatemala is renowned for its impressive Mayan archaeological sites, such as Tikal, which offers spectacular views of the ruins atop the jungle.",
    isFavorite: false,
    Capital: "Guatemala City",
    CountryCode: "gt",
    Currency: "GTQ",
    TimeZone: "",
  },
  {
    ID: 51,
    Name: "Guyana",
    Src: "https://cdn.pixabay.com/photo/2015/03/17/00/12/beach-bourda-677016_640.jpg",
    Label: "South America",
    Text: "Discover a fascinating country with remarkable natural diversity, vibrant culture, and captivating history.",
    TextDesktop:
      "Guyana is known for its unique biodiversity, including vast tropical forests, savannas, mountains, and magnificent waterfalls.",
    isFavorite: false,
    Capital: "Georgetown",
    CountryCode: "gy",
    Currency: "GYD",
    TimeZone: "",
  },
  {
    ID: 52,
    Name: "Hong Kong",
    Src: "https://cdn.pixabay.com/photo/2019/07/29/10/35/hong-kong-4370342_640.jpg",
    Label: "Asia",
    Text: "The city of Hong Kong is famous for its sparkling skyscrapers, bustling neighborhoods, traditional markets, and culinary delights.",
    TextDesktop:
      "Hong Kong is a major global financial center, with a diverse and dynamic economy. Its port is one of the busiest in the world.",
    isFavorite: false,
    Capital: "Hong Kong",
    CountryCode: "hk",
    Currency: "HKD",
    TimeZone: "",
  },
  {
    ID: 53,
    Name: "Honduras",
    Src: "https://cdn.pixabay.com/photo/2019/05/11/04/06/mahogany-bay-4195083_640.jpg",
    Label: "America",
    Text: "Explore its natural wealth, pristine beaches, fascinating archaeological sites, and vibrant culture.",
    TextDesktop:
      "Honduras is home to incredible biodiversity, with lush tropical forests, majestic mountains, rushing rivers, and spectacular coral reefs.",
    isFavorite: false,
    Capital: "Tegucigalpa",
    CountryCode: "hn",
    Currency: "HNL",
    TimeZone: "",
  },
  {
    ID: 54,
    Name: "Croatia",
    Src: "https://cdn.pixabay.com/photo/2019/05/20/21/45/croatia-4217709_640.jpg",
    Label: "Europe",
    Text: "Discover its beautiful coastline along the Adriatic Sea, with crystal-clear waters, picturesque beaches, and preserved islands.",
    TextDesktop:
      "The country is full of ancient towns and well-preserved historical sites that testify to its rich Roman, Venetian, and medieval past.",
    isFavorite: false,
    Capital: "Zagreb",
    CountryCode: "hr",
    Currency: "HRK",
    TimeZone: "",
  },
  {
    ID: 55,
    Name: "Haiti",
    Src: "https://cdn.pixabay.com/photo/2018/03/22/01/16/body-of-water-3248968_640.jpg",
    Label: "America",
    Text: "Discover a variety of landscapes ranging from white sandy beaches to lush mountains, verdant valleys, and picturesque waterfalls.",
    TextDesktop:
      "Haiti, a Caribbean island, fascinates with its rich history, vibrant culture, and diverse landscapes.",
    isFavorite: false,
    Capital: "Port-au-Prince",
    CountryCode: "ht",
    Currency: "HTG",
    TimeZone: "",
  },
  {
    ID: 56,
    Name: "Hungary",
    Src: "https://cdn.pixabay.com/photo/2016/10/21/14/50/szechenyi-chain-bridge-1758196_640.jpg",
    Label: "Europe",
    Text: "Hungary is renowned for its rich historical heritage, revitalizing thermal baths, and delicious cuisine.",
    TextDesktop:
      "The country also boasts stunning landscapes, picturesque villages, and lively cultural festivals.",
    isFavorite: false,
    Capital: "Budapest",
    CountryCode: "hu",
    Currency: "HUF",
    TimeZone: "",
  },
];

function Home() {
  const isTabletOrMobile = useMediaQuery({ query: "(max-width: 699px)" });
  const isDesktopOrLaptop = useMediaQuery({ query: "(min-width: 700px)" });

  const selectionManager = new CountrySelectionManager();

  const manageLikes = new ManageLikes();

  return (
    <div>
      {isTabletOrMobile && <HeaderNavMobile />}
      {isDesktopOrLaptop && <HeaderNavDesktop />}
      <ModalManager
        selectionManager={selectionManager}
        manageLikes={manageLikes}
      />
      <RecommandedList
        destinations={destinations}
        selectionManager={selectionManager}
        manageLikes={manageLikes}
      />
      <PopularList
        destinations={destinations}
        selectionManager={selectionManager}
        manageLikes={manageLikes}
      />
      <LikeSection
        selectionManager={selectionManager}
        manageLikes={manageLikes}
      />
    </div>
  );
}

export default Home;
